name: 'Rudra'
description: 'Openapi based test coverage for integration tests'
inputs:
  stage:
    description: 'Preperation or evaluation mode'
    required: true
    default: 'evaluation'
runs:
  using: "composite"
  steps:
    - run: echo Mode ${{inputs.stage}}
      shell: bash
    - shell: bash
      run: |
        if [["${{inputs.stage}}", "preperation"]]; then \
          # start nginx
          docker run
        else if [["${{inputs.stage}}"]]; then \
          # kill nginx and test return value
          echo magic docker stop and test \
        else \
          echo "please provide a stage name of either \"preperation\" or \"evaluation\"" \
          exit 1 \
        fi
