name: 'Rudra for OpenAPI test coverage'
author: 'Amos Gross'
description: 'Openapi based test coverage for integration tests'
branding:
  icon: 'wind'
  color: 'purple'
inputs:
  stage:
    description: 'Preperation or evaluation mode'
    required: true
    default: 'evaluation'
  openapi-source: 
    description: 'Path or URL of openapi file (either json or yaml)'
    required: false
  instance-url: 
    description: 'URL of application that will be tested'
    required: false
  account-for-security-forbidden: 
    description: 'Take security tags of spec into account and require all 403 cases to be tested'
    required: false
  account-for-security-unautorized: 
    description: 'Take security tags of spec into account and require all 401 cases to be tested'
    required: false
  debug:
    description: 'Debugging mode'
    required: false
  test-coverage:
    description: 'Percentage of endpoints that should be covered to pass this stage'
    required: false
  port:
    description: 'Port for rudra to listen on'
    required: false
  services:
    description: 'A mapping for multiple services with different specs and basepaths'
    required: false
  only-account-for-pr:
    description: 'Indicates if only the changes of a PR should be taken into account when available'
    required: false
  groupings: 
    description: 'Allows for ignoring or grouping of specific endpoints'
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 
    - shell: bash
      run: |
        if [[ "${{inputs.stage}}" = "preperation" && "$GITHUB_BASE_REF" != "" ]]; then 
            docker network create rudra 
            for line in $(docker ps -q); do 
                docker network connect rudra $line; 
            done 
            RUDRA_APP_BASE_URL=${{inputs.instance-url}}
            if [[ "${{inputs.services}}" = "" ]]; then
                if [[ "${{inputs.port}}" = "" ]]; then
                    RUDRA_PORT="-p 13750:13750"
                else
                    RUDRA_PORT="-p ${{inputs.port}}:${{inputs.port}}"
                fi
                RUDRA_MAPPING=""
                if [[ "$GITHUB_BASE_REF" != "" ]]; then
                    RUDRA_IS_MERGE="1"
                    if [[ -f "${{inputs.openapi-source}}" ]]; then
                        git show ${{github.event.pull_request.base.sha}}:${{inputs.openapi-source}} > ${{inputs.openapi-source}}.rudra.old
                    fi
                else
                    RUDRA_IS_MERGE="0"
                fi
            else
                RUDRA_PORT="$(echo "${{inputs.services}}" | sed -r 's/([^;]|\\;)*;([^;]|\\;)*; ([0-9]+)\;/-p \3:\3/g' | sed 's/localhost/172.17.0.1/g' | tr '\n' ' ')"
                RUDRA_MAPPING="${{inputs.services}}"
                RUDRA_MAPPING="${RUDRA_MAPPING//$'\n'/RUDRA_LINE_SEPERATOR}"
                RUDRA_MAPPING="${RUDRA_MAPPING//localhost/172.17.0.1}"
                if [[ "$GITHUB_BASE_REF" != "" ]]; then
                    RUDRA_IS_MERGE="1"
                    for spec in $(echo $RUDRA_MAPPING | sed -r 's/([^;]|\\;)*;\W?(([^;]|\\;)*); ([0-9]+)\;/\2 /g'); do 
                        if [[ -f "$spec" ]]; then
                            git show ${{github.event.pull_request.base.sha}}:$spec > $spec.rudra.old
                        fi
                    done
                else
                    RUDRA_IS_MERGE="0"
                fi
            fi
            docker run --env RUDRA_DEBUG="${{inputs.debug}}" --env RUDRA_APP_BASE_URL="${RUDRA_APP_BASE_URL/localhost/172.17.0.1}" --env RUDRA_OPENAPI_SOURCE="${{inputs.openapi-source}}" --env RUDRA_ACCOUNT_FOR_FORBIDDEN="${{inputs.account-for-security-forbidden}}" --env RUDRA_ACCOUNT_FOR_UNAUTORIZED="${{inputs.account-for-security-unautorized}}" --env RUDRA_TEST_COVERAGE="${{inputs.test-coverage}}" --env RUDRA_PORT="${{inputs.port}}" --volume $PWD:/repo $RUDRA_PORT --env RUDRA_MAPPING="$RUDRA_MAPPING" --env RUDRA_IS_MERGE="$RUDRA_IS_MERGE" --env RUDRA_ONLY_ACCOUNT_MERGE="${{inputs.only-account-for-pr}}" --env RUDRA_GROUPINGS="${{inputs.groupings}}" --network rudra --name rudra -d grossamos/rudra:v0.1.2
            sleep 1
            docker logs rudra
            exit $(docker container inspect --format '{{.State.ExitCode}}' rudra) 
        fi
    - shell: bash
      run: |
        if [[ "${{inputs.stage}}" = "evaluation" ]]; then 
            if [[ "${{inputs.openapi-source}}" != "" || "${{inputs.instance-url}}" != "" || "${{inputs.test-coverage}}" != "" || "${{inputs.debug}}" != "" || "${{inputs.account-for-security-unautorized}}" != "" || "${{inputs.account-for-security-forbidden}}" != "" || "${{inputs.services}}" != "" ]]; then 
                echo "Please configure rudra in the preperation stage and do not add configuration parameters (outside of stage) here" 
                exit 1 
            fi 
            docker exec rudra nginx -s stop 
            sleep 1
            docker logs rudra
            exit $(docker container inspect --format '{{.State.ExitCode}}' rudra) 
        fi
    - shell: bash
      run: |
        if [[ "${{inputs.stage}}" != "evaluation" && "${{inputs.stage}}" != "preperation" ]]; then 
            echo "Please provide a stage name of either \"preperation\" or \"evaluation\"" 
            exit 1 
        fi 

