baseURL = "/"
languageCode = "en-us"
title = "Rudra"
theme = "kube"
description = "Rudra is an openapi-centered tool for measuring test coverage in integration tests."
Paginate = 4
[Params]
  author = "" # add your company name
  github = "" # add your github profile name
  twitter = "" # add your twitter profile
  email = "contact@rudra.cloud"

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Github"
    weight = -100
    url = "https://github.com/grossamos/rudra"
[[menu.main]]
    name = "Faq"
    weight = -100
    url = "/faq/"
